- poetry.lock
- pyproject.toml
- snakefmt/formatter.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- tests/test_formatter.py
- tests/test_parser.py
- tests/test_snakefmt.py
Here are the added features:
* Parameter keywords can occur inside python code
* Some parameter keywords can occur multicopy, eg `include`
* Better comment handling: they could get absorbed by parameter keywords
* Triple quoted string handling in `shell`
All 71 unit tests pass, and additionally I have run `snakefmt` on the snakefiles inside `https://github.com/snakemake-workflows`: dna-seq-varlociraptor, dna-seq-gatk-variant-calling, rna-seq-star-deseq2, single-cell-rna-seq, single-cell-drop-seq
> Bugfixes and better formatting

- poetry.lock
- pyproject.toml
- snakefmt/exceptions.py
- snakefmt/formatter.py
- snakefmt/snakefmt.py
- tests/__init__.py
- tests/test_formatter.py
- tests/test_snakefmt.py
This PR closes #3 
- Read `snakefmt` setting from (TOML) file passed to `--config`. If `--config` is not given, the current directory is searched for `pyproject.toml` and attempts to read settings from that [#3].
- In a similar manner to the previous, `black` settings are also read from whichever file was used to get `snakefmt` settings. `snakefmt` settings always take precedent [#3].
- Allowed formatting Snakefile from stdin [#4]
- Increased minimum versions required for `snakemake` and `click` due to failing tests on older versions.
In addition, this PR contains one failing test: https://github.com/mbhall88/snakefmt/blob/f9c970870060b43d612f1db2fbaed2edd7df9469/tests/test_snakefmt.py#L108-L136
See #29 for more details
> Allow reading settings from configuration file

- .flake8
- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- codecov.yml
- poetry.lock
- pyproject.toml
- snakefmt/formatter.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
This PR closes #16 
It adds GitHub Actions continuous integration for 
- Linting - via `flake8`
- Formatting - via `black`
- Testing - via `pytest`
- Code coverage report - via codecov
> Set up continuous integration workflow

- .flake8
- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- codecov.yml
- poetry.lock
- pyproject.toml
- snakefmt/diff.py
- snakefmt/formatter.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- tests/test_diff.py
- tests/test_formatter.py
- tests/test_grammar.py
- tests/test_parser.py
- tests/test_snakefmt.py
This PR closes #5 and #6 
- `--check` option to allow checking whether any changes would be made and returning an exit code relevant to the result [#5]
- `--diff` and `--compact-diff` options to allow checking what changes would be made without writing back to file [#6]
- `Diff` class that is used for dealing with the check and diff options.
- Various tests to increase coverage
- Badges! :tada: 
- Writing back to file when formatting files. (We were just printing to screen until now).
- Full usage in README with new options
- Documenting check and diff options in README
- flake8 fixes in the test directory so now the CI runs flake8 on the entire project.
> Add diff and check options

- .flake8
- snakefmt/formatter.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/types.py
- tests/conftest.py
- tests/test_config.py
- tests/test_formatter.py
- tests/test_grammar.py
- tests/test_snakefmt.py
This PR closes #29 and #33 and refactors tests
* Bugfixes in formatting for the two issues mentioned above
* While processing both, I (of course...) hit some other formatting bugs/issues. I have added them as 3 failing tests. We can add them as issues. They are:
* Triple quoted strings can get overindented for eg in `shell` context
* Python code preceding nested snakecode does not get `black`ed
* Python code following nested snakecode gets `black`ed but is an issue
The last two are totally related and should go in same issue. The first one doesn't really have to be an issue, not sure.
* Added `configfile` as possibly duplicated keyword (#27), and a grammar test testing duplicated keywords pass.
* I refactored tests relating to configuration (pyproject.toml, user-specified toml, black toml …
> Bugfixes and refactoring

- pyproject.toml
- snakefmt/diff.py
- snakefmt/formatter.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- tests/test_config.py
- tests/test_diff.py
- tests/test_formatter.py
- tests/test_grammar.py
- tests/test_parser.py
- tests/test_snakefmt.py
* Removed `Enum` based comparisons and unit tests: simplifies our codebase at no cost
* Type annotations, function doscstrings and comments for future us/helping understanding
* Python code preceding a nested (=indented) snakemake keyword/context gets formatted with `black`. This meant solving a formatted line being a lone `else:` for example, which is invalid python syntax. Solves #40 , #41
* Triple quoted string indenting. Solves #39
* Newline paradigm: two newlines between top level elements, one newline in nested context. This mirrors black. `rule` is basically treated like a python class/function in this respect. Solves #40
* Comments: they get tagged along elements, following what black does. If a comment occurs just before a `rule` (or an `include`, or any other top level keyword- …
> Bugfixes, addressed issues and simplifications

- README.md
- snakefmt/parser/grammar.py
- snakefmt/snakefmt.py
- tests/test_formatter.py
- tests/test_snakefmt.py
* Removed some unnecessary error checks in snakefmt/get_snakefiles_in_dir function. These were in place for checking a file relative to the root of a project (black code), but we don't do that. Improves coverage for free ;-)
* More  info at command line about modifying files in place and advertise `-h` for help
* Add a test for comments after keywords
> Improve test coverage and add cmdline info

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- poetry.lock
- pyproject.toml
- snakefmt/__init__.py
- snakefmt/formatter.py
- tests/test_formatter.py
> Fix: triple-quoted f-strings

- README.md
This PR adds a section to the README which explains how to use `snakefmt` with GitHub Actions and `super-linter`.
> Add GitHub Actions README section

- CHANGELOG.md
- README.md
- pyproject.toml
- snakefmt/formatter.py
- snakefmt/snakefmt.py
- tests/test_config.py
- tests/test_snakefmt.py
Closes #73 
- `black` config was not being used if it did not contain `[tool.snakefmt]` [#73]
- better handling of `black.FileMode` params [#73]
> Use black config even if no snakefmt settings

- README.md
- docs/editor_integration.md
- plugin/snakefmt.vim
- snakefmt/formatter.py
- snakefmt/snakefmt.py
- tests/__init__.py
- tests/test_config.py
This PR adds a vim plugin as per #62 and also streamlines config parsing. I did this to enforce better consistency of config parsing and to enable vim plugin to parse configuration just like snakefmt does.
* Vim plugin, with instructions on how to install and automatically run it.
The vim plugin also reads toml configuration in the same way `snakefmt` does.
* New searching for default `pyproject.toml`. Before was based on current workdir,
now based on formatted file(s) (passed as `src` param at CLI) location. Use black code for this. With unit tests.
* Single `line_length` in the `Formatter` class. Previously black and snakefmt toml
`line_length`s were kept separate. Now both set it, and snakefmt's, if set, overrides black.
* Refactored toml parsing in `snakefmt.py` into 3 functions for …
> Vim plugin and new snakefmt configuration code

- docs/editor_integration.md
- plugin/snakefmt.vim
First of all thanks for `snakefmt` and the Vim plugin! When I first attempted to install `snakefmt` into an existing `conda` env I ran into an issue where, when using Vim complied with Python 3, I would get the error (print statement):
```bash
snakefmt not found. Is snakefmt installed?
```
I was initially confused as I had just installed `snakefmt` and could use it from the command line. It turns out that the `try` block was catching a `ModuleNotFoundError` from _Black_ due to an import issue with `regex` as documented [here](https://black.readthedocs.io/en/stable/editor_integration.html#vim).
To avoid this, I moved all but the `snakefmt_version` import out of the try block so that the `snakefmt not found` print statement only occurs when `snakefmt` isn't installed. In case others run …
> Isolate plugin import try block, format with black

- .pre-commit-hooks.yaml
- README.md
It would be nice if snakefmt would work as easily with [pre-commit ](https://pre-commit.com/) as black. This PR copies the .pre-commit-hooks.yaml from the black repository and modifies it for snakefmt. 
Users could then point directly at the snakefmt repository in their `.pre-commit-config.yaml` and have snakefmt automatically run on `*.smk` and `Snakefile`.
Here is an example of what the config would look like pointing at my repo.
```yaml
-   repo: https://github.com/jfear/snakefmt
rev: b4e365145107371a20e24dc3808230fef24feacf
hooks:
-   id: snakefmt
```
I don't know if the maintainers would want to include this kind of metadata. However, since the psf/black has I thought I would ask.
> Adds pre-commit hook metadata.

- CHANGELOG.md
- README.md
- snakefmt/formatter.py
- tests/test_formatter.py
* Propose a fix for #78 , with a unit test containing the previously failing example in that issue
* Update changelog, with contributions from others
@mbhall88 should we do a new release after these changes?
> Address #78

- .gitignore
- plugin/snakefmt.vim
- snakefmt/config.py
- snakefmt/formatter.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- snakefmt/types.py
- snakefmt/warnings.py
- tests/conftest.py
- tests/test_config.py
- tests/test_formatter.py
- tests/test_parser.py
- tests/test_snakefmt.py
This PR mainly addresses #85, providing better formatting of comments.
It also adds code infrastructure for issuing warnings and ungetting tokens.
* Infrastructure for issuing warnings in warnings.py. Warnings introduced for comment formatting, as per #85.
* File-specific logging: warnings and errors during reformatting now automatically refer
to the raising source file.
* Infrastructure to 'unget' parsed tokens. Not used yet, but useful to have. With tests.
(All these bugs documented in #85)
* Comments above keywords stay untouched
* Inline comments in inline-formatted keywords get relocated above keyword
* PEP8 inline comment formatting: use 2 spaces
With tests for each.
* Refactored config-related code out of `snakefmt.py` and `formatter.py` to own source 
file, `config.py`
> Better comment formatting

- CHANGELOG.md
- pyproject.toml
Fixes three issues (89, 91, 91). 89 is quite pressing because it shows we lost support for Python3.6 and Python3.7
in v0.2.5.﻿
> Bump version to 0.2.6

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- snakefmt/parser/grammar.py
- tests/test_formatter.py
- tests/test_snakefmt.py
Objective: update snakefmt to use latest version of black
(Background: this issue has lead to a bit of a headache over at https://github.com/github/super-linter/issues?q=is%3Aissue+black+ and it seems best to address it at the root project)
Note: clearly, this is a breaking change (see unit tests) which I assume will require a major version update of the package. That said, if the aim of this package is "It follows the design and specifications of Black.", it seems like it might make sense to track formatting decisions the black project.
@mbhall88 I'm happy to see this PR through to the end, so if you have feedback about missing elements, etc., just let me know and I'll have another go at the PR. :)
> Update click, toml and black (major version) to latest releases

- CHANGELOG.md
- pyproject.toml
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- tests/test_formatter.py
- tests/test_parser.py
Fixes two bugs (see below).
One point for discussion is it does not fix #104 and #105 whereby empty `input:` is not allowed by us; i don't think it's technically allowed by snakemake grammar either, but is allowed in practice. Not sure what to do there.
* Add support for multiple anonymous rules, as per [snakemake grammar](https://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html#grammar) (#103)
* Newline bug in `use` syntax (#106)
> Release 0.4.1

- poetry.lock
- pyproject.toml
Upgrade to the latest release of `black`.
This allows downstream projects like [Github's super-linter](https://github.com/github/super-linter/) to upgrade `black` as well.
I am seeing some test failures, but haven't been able to pin down what about the `black` upgrade is causing the breakage.
> Upgrade black to 21.7b0

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- snakefmt/parser/grammar.py
- tests/test_snakefmt.py
Part of the reason #116 was failing tests was a missing `handover` keyword that was added in [`snakemake` v6.2.0](https://github.com/snakemake/snakemake/blob/main/CHANGELOG.rst#620---2021-04-22). I've added that in and updated the lock file due to some other issues alluded to in #116
I've also pre-emptively bumped the version so that when this is merged onto master we can just tag a release on github directly.
> Add missing handover keyword

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- snakefmt/__init__.py
- snakefmt/formatter.py
- snakefmt/parser/grammar.py
- tests/test_parser.py
- tests/test_snakefmt.py
* Collapsing of multi-line strings does not cause syntax error now [[#118][118]]
* Version detection adapts to python version
This PR addresses #118 
Basically, what was happening was list comprehension was being collapsed and causing invalid syntax
```py
sample=[
i
for i in pd.unique(
samples_table[samples_table["seqmode"] == "pe"].index.values
)
],
```
was collapsing so that we were passing something like `[ifor i...` to `black` 
I recommend we hold off on a release until #121 is also sorted
PPS you can ignore the first two commits on this PR as these are just commits on master that weren't already on dev
> Add spacing in multiline strings

- CHANGELOG.md
- Makefile
- poetry.lock
- pyproject.toml
- snakefmt/config.py
- tests/test_snakefmt.py
* Updated black dependency to stable version (v22.1.0). See [the release changes](https://github.com/psf/black/releases/tag/22.1.0) 
for details of style changes. This also required updating click to v8.0.0. (Will close #132)
This will require a minor version bump once merged into `master` as it might cause some style changes (though nothing major I think).
> Update to stable release of black

- CHANGELOG.md
- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
- snakefmt/formatter.py
- snakefmt/parser/grammar.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- tests/test_formatter.py
* Support for `retries` keyword [closes #145]
* Keyword argument lambdas are now allowed inside rules [closes #135]
* Improve reported line number in Snakefile when black fails to parse [closes #127]
* A fix for #126
> fix: Lambda keyword args, improve errors, and nested madness

- snakefmt/parser/syntax.py
- tests/test_formatter.py
Introduced by https://github.com/snakemake/snakemake/pull/1717
> feat: add support for new exclude expressions in use rule statements

- .github/workflows/ci.yaml
- Makefile
- poetry.lock
- pyproject.toml
- snakefmt/parser/grammar.py
fix: relax the `importlib_metadata` version pinning and only install it when the user is using python 3.7 [closes #162]
> feat: add support for resource_scopes directive

- pyproject.toml
This updates the build backend to the new preferred, lightweight [`poetry-core`](https://github.com/python-poetry/poetry-core#why-is-this-required):
> Prior to the release of version `1.1.0`, Poetry was a project management tool that included a PEP 517 build backend. This was inefficient and time consuming when a PEP 517 build was required... This makes PEP 517 builds extremely fast for Poetry managed packages.
This change is especially helpful for distributors (such as Homebrew) to build from source without requiring all of `poetry`.
> build: use lighter poety-core

- CITATION.cff
- snakefmt/snakefmt.py
> fix: make default exclude regex more specific [#202]

- poetry.lock
- pyproject.toml
- snakefmt/__init__.py
- snakefmt/config.py
- snakefmt/formatter.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- tests/test_config.py
- tests/test_formatter.py
- tests/test_grammar.py
- tests/test_parser.py
This PR closes #215, which was caused by the different f-string tokenizing in python 3.12. We had previously dealt with this (#213), but this was only in snakemake code. #215 relates to python code outside of snakemake code (i.e. outside of rules).
The PR also updates black to [v24.1](https://github.com/psf/black/releases/tag/24.1.0), which contains some style changes we need to make some alterations for:
- It enforces a blank line after module strings (`"""module string"""`). We had some test cases where we allow multiple module strings to be passed to rule directives such as `shell` and `message`, so I had to add some code to remove black's added newline in these cases.
- docstrings are aligned correctly now, which required a slight alteration to the expected output of one test
- better …
> feat: update to black v24 and fix double curly braces

- poetry.lock
- pyproject.toml
- snakefmt/__init__.py
- snakefmt/config.py
- snakefmt/formatter.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- snakefmt/snakefmt.py
- tests/test_config.py
- tests/test_formatter.py
- tests/test_grammar.py
- tests/test_parser.py
Ok, I mistakenly closed #216, here's #216 + my two commits
@mbhall88 can you please respond to my comments on #216 and see if you're happy with my two added commits?
We can then keep updating this branch here.
Brice
> feat: update to black v24 and fix double curly braces (Updated PR #216)

- snakefmt/__init__.py
- snakefmt/parser/parser.py
- snakefmt/parser/syntax.py
- tests/test_formatter.py
Same as #228 but having properly rebased on top of master!
> fix: Better f-string spacing (2)

- README.md
Hi,
I realised that from your release `0.5.0` to `0.6.0` the labels switched from `0.5.0` to `v0.6.0`.
Therefore, the example pre-commit snippet in the README is still correct, but once somebody wants to go beyond by just updating the number (as I did) they will get an error from pre-commit.
I think it would be nice to update this small section. Here is a suggestion for the fix with the newest `snakefmt` version.
> docs: update pre commit example
