snakemake/snakefmt

snakefmt/__main__.py

this PR adds `python -m snakefmt` functionality, instead of the current `python -m snakefmt.snakefmt` requirement.
Also supports exit status reporting.

add a __main__ submodule to permit -m execution

---

snakefmt/formatter.py
snakefmt/parser/grammar.py
snakefmt/parser/parser.py
snakefmt/parser/syntax.py
snakefmt/snakefmt.py
tests/test_formatter.py
tests/test_parser.py

Newline formatting, PEP8 formatting, shell and keyword formatting.

Better formatting

---

poetry.lock
snakefmt/exceptions.py
snakefmt/formatter.py
snakefmt/parser/grammar.py
snakefmt/parser/parser.py
snakefmt/parser/syntax.py
snakefmt/snakefmt.py
snakefmt/types.py
tests/__init__.py
tests/test_formatter.py
tests/test_grammar.py
tests/test_parser.py

Since the last PR to dev:
* Can have snakecode inside python code, with unit tests
* New parameter syntax validation and formatting, supporting dictionary unpacking (**)
* Grammar is now tracked for completeness against that of snakemake's

More complete parsing and formatting

---

poetry.lock
pyproject.toml
snakefmt/exceptions.py
snakefmt/formatter.py
snakefmt/snakefmt.py
tests/__init__.py
tests/test_formatter.py
tests/test_snakefmt.py

Allow passing parameters for snakefmt and black via configuration file

---

CHANGELOG.md
README.md
docs/editor_integration.md

- Editor integration instructions for PyCharm
- Instructions for adding badge
- CHANGELOG template from <https://keepachangelog.com/en/1.0.0/>
- Instructions for using configuration (`pyproject.toml`) file
- Added a few examples to the example file
- Fixed weird tab/indentation in the example file code snippet

README updates

---

.github/workflows/release.yaml
README.md

Addresses #45 
- PyPi publish workflow
- DockerHub deploy workflow
- Installation instructions for different platforms
- Badges in anticipation of release (they won't work until after the release).

Release prep

---

snakefmt/formatter.py
snakefmt/parser/parser.py
snakefmt/parser/syntax.py
tests/test_formatter.py

* Bugfix: #51
* More docstring and comment documentation, in an effort to make the codebase easier to understand

Bugfix + more documentation

---

.github/CODEOWNERS
CHANGELOG.md
snakefmt/parser/parser.py
snakefmt/parser/syntax.py
tests/test_formatter.py

As per #61, with a unit test
Also rephrased some docstrings

Reduce greedy comment parsing in keyword context

---

CHANGELOG.md
poetry.lock
pyproject.toml
snakefmt/__init__.py
snakefmt/parser/grammar.py

Changes that fix #61 and #65 
@bricoletc once you are happy to merge this I will push a new release that should also (hopefully) fix https://github.com/bioconda/bioconda-recipes/pull/24238

Fix version number gathering and comment alignment

---

CHANGELOG.md
snakefmt/snakefmt.py
tests/test_snakefmt.py

This PR closes #68 
- allow `--check` and `--diff` to be used together [#68]

Allow check and diff together

---

CHANGELOG.md
pyproject.toml
snakefmt/formatter.py
snakefmt/parser/syntax.py
snakefmt/snakefmt.py
tests/test_formatter.py
tests/test_snakefmt.py

- repeated top-level, single-parameter keywords get placed on consecutive lines [#67]
- allow `--check` and `--diff` to be used together [#68]

Updates for release v0.2.0

---

poetry.lock
snakefmt/parser/grammar.py
snakefmt/snakefmt.py

See https://snakemake.readthedocs.io/en/v5.25.0/snakefiles/rules.html#defining-scatter-gather-processes

add new scattergather directive to the grammar

---

CHANGELOG.md
README.md
pyproject.toml
snakefmt/formatter.py
snakefmt/snakefmt.py
tests/test_config.py
tests/test_snakefmt.py

I've been running these changes for 4-5 days now and everything seems fine. 
@kpj has also confirmed it fixes #73

Changes to go into release 0.2.2

---

docs/editor_integration.md

Resolves https://github.com/snakemake/snakefmt/issues/80

docs: Add visual studio code installation instructions

---

CHANGELOG.md
pyproject.toml
snakefmt/formatter.py
snakefmt/parser/syntax.py
snakefmt/types.py
tests/test_formatter.py

(From changelog)
* Three parsing-related bugs:
- Complex lambda function syntax ([#108][108])
- Argument unpacking ([#109][109])
- Multiline parameters ([#111][111])

Fix three parsing bugs and bump version

---

CHANGELOG.md
Makefile
README.md
poetry.lock
pyproject.toml
snakefmt/config.py
snakefmt/exceptions.py
snakefmt/parser/grammar.py
snakefmt/parser/parser.py
snakefmt/parser/syntax.py
tests/test_formatter.py
tests/test_parser.py
tests/test_snakefmt.py

This PR merges the changes on `dev` that will be part of version 0.5.0

Release v0.5.0

---

CHANGELOG.md
poetry.lock
pyproject.toml
snakefmt/formatter.py
snakefmt/parser/grammar.py
snakefmt/parser/parser.py
snakefmt/parser/syntax.py
snakefmt/snakefmt.py
tests/test_formatter.py

I have been testing dev for a little while now so I think it's ready. Happy to wait a little longer though if we want further testing?

chore: Prepare for release of 0.6.1

---

poetry.lock
snakefmt/formatter.py
snakefmt/logging.py
snakefmt/parser/parser.py
tests/__init__.py
tests/test_formatter.py

fix: multiline string alignment and spacing after keywords

---

poetry.lock
pyproject.toml
snakefmt/formatter.py
snakefmt/parser/parser.py
tests/test_formatter.py

This closes #169, closes #171 and closes #172

Resolve various comment and consecutive directive spacing issues

---

snakefmt/snakefmt.py

fix: add .template to default excludes

---

snakefmt/snakefmt.py

fix: only show diff for changed files

---

snakefmt/parser/syntax.py

fix: don't raise NotAnIdentifier function

---

snakefmt/parser/syntax.py
tests/test_parser.py

fix: raise error on empty named param

---

snakefmt/parser/parser.py
tests/test_formatter.py

fix: handle decorators after snakecode

---

poetry.lock
snakefmt/parser/grammar.py

+ updated snakemake dev-dependency to latest (7.25.0)

fix: add localrule directive (#187)
